dbt_tutorial:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: "{{ env_var('WAREHOUSE_USER') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD') }}"
      dbname: "{{ env_var('WAREHOUSE_DB') }}"
      schema: analytics
      threads: 4